import { Lexend } from 'next/font/google';
import { PropsWithChildren } from 'react';

const lexend = Lexend({ subsets: ['latin'] });

export const metadata = {
  title: 'TEAM.UP',
  description: 'Generated by create next app'
};

const Layout = ({ children }: PropsWithChildren) => {
  return <div className={lexend.className}>{children}</div>;
};

export default Layout;
