import './globals.css';
import { Montserrat } from 'next/font/google';
import { PropsWithChildren } from 'react';
import PageContainer from '@/components/page-container/PageContainer';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata = {
  title: 'Wordsy',
  description: 'Generated by create next app'
};

const Layout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} h-screen overflow-hidden p-12 box-border`}>
        <PageContainer>{children}</PageContainer>
      </body>
    </html>
  );
};

export default Layout;
